### PR TITLE
fix: several typos in the documentation

### PR DESCRIPTION
**Pull request by tudorpintea999**
Hello
I fixed some typos in the docs,
Hope it helps.
Br,
Tudor.

### CODE REVIEW

**Review by zzq0826 — APPROVED** [review]

**Comment by zzq0826** [comment]
LGTM! Thanks

**Comment by tudorpintea999** [comment]
@zzq0826 thanks ! i see this gitpoap https://www.gitpoap.io/gp/1057 . are my changes suitable to get one ? i also raised an issue to get one but still no answer 🤝

**Comment by MALIKSHAHID786** [comment]
Hi

**Comment by porridgecannon** [comment]
There's only 6 holders this year, I doubt simply fixing typos is enough

**Pull request merged**
