### PR TITLE
Upgrade astro version v4

### PR DESCRIPTION
**Pull request by zzq0826**
- [x] Support view transitions
- [x] https://docs.scroll.io/zh/ should show or redirect to frontpage (https://docs.scroll.io/zh/home/)
- [x] Sub header anchor links 
- [x] i18n support for search

### CODE REVIEW

**Comment by dghelm** [comment]
Images are no longer allowing for "zoom" as in this page: https://deploy-preview-220.docs.scroll.xyz/en/technology/

**Comment by zzq0826** [comment]
> Images are no longer allowing for "zoom" as in this page: https://deploy-preview-220.docs.scroll.xyz/en/technology/

image
Are you referring to this feature? It works for me, it might require the page to be fully loaded?

**Comment by dghelm** [comment]
Two bugs fixed:
- flash of unformatted header (darkmode icon?) caused search bar and tools item to "jump" on page transition
- page transitions default to fade (despite being marked as none) if initial load is on homepage, not an article page

Also, moved ViewTransition invocation logic from Header (UI element) to HeadCommon (lives in `<Head>`)

For follow-up: Can we move to a shared <head> tag between different pages? Would this let us use a transition with expected behavior?

**Comment by dghelm** [comment]
For follow-up (low priority): Can we maintain page transition across translation shifts when language selector is used?

**Review by dghelm — APPROVED** [review]

**Pull request merged**
